### ISSUE TITLE
Recognize number noun prefixes with `_or_more` keyword

### ISSUE THREAD

**Issue by EmilySeville7cfg** [command-line-interface-pages/v2-tooling#42]
## Description

Intended to support prefixes:

- one
- two
- three
- four
- five
- six
- seven
- eight
- nine

## Motivation

Why? Because it's not always possible to detect how much repetitions are expected. And even if lowest repetition count is detected it's not possible to figure out what the highest limit is: TlDr syntax limitation.

Let's say we have this input: `{{path/to/file1}} {{path/to/file1 path/to/file2 ...}}`. How to treat it?  Is it a one required file and 0..more separate ones? Or they are all the same and 1..more files expected? Placeholder numbering is not standardized in TlDr so that's why it's not something script can rely on (even it should decide how to interpret placeholders).

## Example

- Input: `{{path/to/two_files}}`
  Output: `{/?file 2..2 some description}`

- Input: `{{path/to/two_remote_files}}`
  Output: `{/?file 2..2 remote file}`

- Input: `{{path/to/two_or_more_files}}`
  Output: `{/?file 2.. some description}`

- Input: `{{path/to/two_or_more_remote_files}}`
  Output: `{/?file 2.. remote file}`

## Implementation details

Such prefixes should be checked before checking arbitrary file prefix like `{{path/to/image_file}}` to be recognized (in sed code).

🤔 Maybe implement a more reliable parser first as supporting tons of sed regexes is not easy even after refactoring.

**Comment by EmilySeville7cfg** [comment]
@mfrw, @kbdharun, @navarroaxel, what do u think about such idea? This just requires from you to update TlDr pages to support such prefixes.

**Comment by blueskyson** [comment]
Changing {{path/to/file1 path/to/file2 ...}} to {{path/to/one_or_more_files}} works in my opinion. But I think {{path/to/file1 path/to/file2 ...}} is a little better for readability.
